# Generated by Django 5.0 on 2023-12-08 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.patientinfo'),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='patientinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.patientinfo'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patientinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.patientinfo'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicalhistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.medicalhistory'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patientinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.patientinfo'),
        ),
    ]
